### ISSUE TITLE
伝票を起こす事をAPIで把握できますか？

### ISSUE THREAD

**Issue by kichi-t** [ubiregiinc/ubiregi-api#86]
ユビレジのIpad操作ログでは伝票をお越し始めた記録があるかと思います。

レジ開始

これを、伝票を起こしたことだと認識しています。

この情報をAPIで習得することは可能でしょうか？

**Comment by soutaro** [comment]
見落としていました。申し訳ありません。

アプリ操作のログについては、現在は、取得するAPIを公開しておりません。今後、対応するようなことがありましたら再度アナウンスいたします。
