### ISSUE TITLE
sku指定でMenuItemの更新はできないでしょうか

### ISSUE THREAD

**Issue by kubibon** [ubiregiinc/ubiregi-api#89]
MenuItemを更新する場合に 
sku指定で出来るようにできないでしょうか。

 #42 をみると
複数skuを指定しMenuItem 取得はできるようですが、更新となると

複数skuを指定し → MenuItem 取得 → 取得したidを使用して  → MenuItem POST
…となるので、できれば1リクエストで済ませてしまいたいのです。

用途としては 下記のようなリクエストを投げて
複数のskuを指定し価格の一括変更を想定しています。
難しいでしょうか。
{
  "items": [
		{"sku": "test001","price": 123},
		{"sku": "test002","price": 456}
	]
}

**Comment by soutaro** [comment]
返事が遅くなってすみません。

モチベーションは理解できるのですが、すぐに対応する予定はありません。SKUでアイテムを取得後、改めての更新でお願いします。現在、SKUは更新可能なフィールドなので、更新のキーとして利用できるのは不適切であると考えています。

**Comment by kubibon** [comment]
ご確認ありがとうございます。
なるほど、SKUはユニークではあるが、変更可能である為
更新のキーとしては適さないということですね。
理由としては納得しました。

※ただ、今後も同要望がでましたら検討していただければ助かります。
